FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

RUN pecl channel-update pecl.php.net \
    && (pecl list | grep -q xdebug || pecl install xdebug) \
    && docker-php-ext-enable xdebug



# Настройка Xdebug
COPY  "/docker/php/conf.d/xdebug.ini" "/usr/local/etc/php/conf.d/xdebug.ini"
