version: '1'

services:
  nginx:
    image: nginx:1.25.5
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/config-nginx:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/html
    depends_on:
      - php
    restart: always
  
  php:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
      - ./src:/usr/share/nginx/html
    restart: always

  varnish:
    build:
      context: .
      dockerfile: ./docker/varnish/dockerfile
    ports:
      - "80:80"
    depends_on:
      - nginx